[Settings]
[build]
  publish = "public/"
  command = "yarn run build:netlify"

# Redirect from old blog path to new posts path
[[redirects]]
  from = "/blog/*"
  to = "/posts/:splat"
  status = 301

# Redirect from netlify to main domain
[[redirects]]
  from = "https://kaihao-dev.netlify.com/*"
  to = "https://kaihao.dev/:splat"
  status = 301
  force = true

# Redirect from old kaihao.info domain to main domain
[[redirects]]
  from = "https://kaihao.info/*"
  to = "https://kaihao.dev/:splat"
  status = 301
  force = true

# Redirect from some popular old sites to their new url
[[redirects]]
  from = "https://kaihao.dev/BeanfunLogin"
  to = "https://kevin940726.github.io/BeanfunLogin"
  status = 301
  force = true
[[redirects]]
  from = "https://kaihao.dev/minesweeper"
  to = "https://kevin940726.github.io/minesweeper"
  status = 301
  force = true

[[headers]]
  for = "/cosmos/*"

  # react-cosmos will inject an iframe inside the app for preview.
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self' https://www.facebook.com"
    # Disable cache for react-cosmos site
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
